### ISSUE TITLE
bloat in published npm package

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [nperf/nlapack#45]
I noticed when updating nlapack from 2.0.4 to 2.0.8 that its size grew by somewhere between 10-20x!

Some investigations identified the major culprits:
* The docs directory is much larger now
* The `cc-reporter` binary for code climate is being included in the published npm package :exclamation: 

This affects nblas too.

Some judicious editing of `.npmignore` or `package.json`'s `files` section would help a lot here.

**Comment by mateogianolio** [comment]
Wow thank you for submitting this issue and nice catch! Fix will be published soon.
